### PR TITLE
adding missing paper 

### PR DESCRIPTION
**Pull request by timdoster0**
this should be the missing pdf for migus22a and an updated pdf for myers22a.

### CODE REVIEW

**Comment by lawrennd** [comment]
Thanks Tim! Can you give a description of why the changes are requested so we have that for the record.

Also the .txt format won't compile, you need to provide it as a .md.

**Comment by timdoster0** [comment]
i tried to update this but honestly im not a git expert.

-Tim

**Comment by lawrennd** [comment]
Don’t worry, you don’t need to be, performing a pull request is described here:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

From: Tim Doster ***@***.***>
Date: Wednesday, 25 January 2023 at 07:05
To: mlresearch/v196 ***@***.***>
Cc: Neil Lawrence ***@***.***>, Comment ***@***.***>
Subject: Re: [mlresearch/v196] adding missing paper (PR #13)
i tried to update this but honestly im not a git expert.

-Tim

**Comment by timdoster0** [comment]
ok let me know if that is better

-Tim

**Review by lawrennd — APPROVED** [review]
Looks good to me.

**Comment by lawrennd** [comment]
Thanks Tim, looks good. Can you just provide the explanation for why the paper needed to be added here for the record? Then I can merge.

**Comment by timdoster0** [comment]
Yes. The original paper was mistaken omitted from the submission due to it getting caught in the spam folder. -TimSent from my iPhoneOn Jan 27, 2023, at 11:17 PM, Neil Lawrence ***@***.***> wrote:﻿
Thanks Tim, looks good. Can you just provide the explanation for why the paper needed to be added here for the record? Then I can merge.

**Review by lawrennd — APPROVED** [review]
Looks good to me.

**Review by lawrennd — COMMENTED** [review]
Looks good to me.

**Pull request merged**
